name: 'Find Globals'
description: 'Find globals for WoW addon'
inputs:
  find-args:
    description: 'Arguments to find, can be used to ignore files and directories.'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Install Lua 5.1.5
      uses: leafo/gh-actions-lua@v12.0.0
      with:
        luaVersion: "5.1.5"

    - name: Parse globals from wow-ui-source
      run: |
        result=$(find . -name "*.lua" -type f ! -path "./.lua/*" ! -path "./.install/*" ${{ inputs.find-args }} | xargs -n1 -I {} bash -c "luac -l -p {} | lua $GITHUB_ACTION_PATH/globals.lua {}")
        echo "$result"
        ! [[ $result ]]
      shell: bash

    - name: Clean up
      run: rm -rf .lua .install
      shell: bash
